#!/bin/bash

# Quick version of compare_benchmarks.sh that doesn't run benchmarks
# Useful for testing the script logic without waiting for full benchmarks

CRITERION_DIR="target/criterion"

echo "Generating comparison tables (using existing benchmark results)..."
echo ""

generate_table() {
    local vec_type="$1"
    local title="$2"

    echo "### $title"
    echo ""
    echo "| Operation | fast_vec (ns) | nalgebra (ns) | Speedup |"
    echo "|-----------|--------------|---------------|---------|"

    # Get all unique operations for this vector type
    local operations=$(ls "$CRITERION_DIR" 2>/dev/null | grep "^fast_vec_" | sed 's/^fast_vec_//' | sort)

    if [ -z "$operations" ]; then
        echo "| (No benchmarks found) | | | |"
        return
    fi

    for op in $operations; do
        local fast_json="$CRITERION_DIR/fast_vec_${op}/new/estimates.json"
        local nalg_json="$CRITERION_DIR/nalgebra_${op}/new/estimates.json"

        if [ -f "$fast_json" ] && [ -f "$nalg_json" ]; then
            local fast_time=$(jq -r '.mean.point_estimate' "$fast_json" 2>/dev/null)
            local nalg_time=$(jq -r '.mean.point_estimate' "$nalg_json" 2>/dev/null)

            if [ -n "$fast_time" ] && [ "$fast_time" != "null" ] &&
               [ -n "$nalg_time" ] && [ "$nalg_time" != "null" ]; then

                if (( $(echo "$fast_time > 0" | bc -l) )); then
                    local speedup=$(echo "scale=2; $nalg_time / $fast_time" | bc -l)
                    printf "| %-20s | %12.2f | %13.2f | %7.2fx |\n" "$op" "$fast_time" "$nalg_time" "$speedup"
                fi
            fi
        fi
    done
    echo ""
}

# Output to terminal
generate_table "Vector2" "Vector2 Benchmarks"
generate_table "Vector3" "Vector3 Benchmarks"

echo "Results saved to BENCHMARK_RESULTS.md"

# Also save to markdown file
{
    echo "# Benchmark Results"
    echo ""
    echo "Comparison between \`fast_vec\` SIMD implementation and \`nalgebra\`"
    echo ""
    echo "Generated by \`scripts/compare_quick.sh\`"

    generate_table "Vector2" "Vector2 Benchmarks"
    generate_table "Vector3" "Vector3 Benchmarks"
} > BENCHMARK_RESULTS.md

echo "Done!"
